### ISSUE TITLE
Inconsistency with `bundle update`

### ISSUE THREAD

**Issue by marcandre** [chrismo/bundler-cases#6]
Here's a [test case](https://github.com/marcandre/bundler-cases/blob/f1d57f49cc4871b5eda803825c649f982fd719ac/cases/conservative/very_basic.rb) aiming to illustrate the inconsistency with `bundle update foo` with different `--major`/`minor`/`patch`. The only available gem versions are patches releases, so all three options should all behave the same but they don't for [the `minor` and `patch` options](https://github.com/marcandre/bundler-cases/blob/f1d57f49cc4871b5eda803825c649f982fd719ac/cases/conservative/very_basic.rb#L43-L59).

I feel this inconsistency has to be bug. For sure, it makes it impossible to understand what is supposed to be going on.

**Comment by chrismo** [comment]
ah! very interesting. `--major` in this case defaults to not using any of the new code mechanisms in order to retain backward compatibility ... the idea being `--major` in 1.x would not change anything, so that in 2.x Bundler (2.0 only in dev right now) the default behavior could be switched to `--patch`.

Obviously something in the new code is affecting things it shouldn't in order to be consistent. Nice test case, thx!

**Comment by chrismo** [comment]
(we should probably file this bug with Bundler itself).

**Comment by marcandre** [comment]
Right, sorry. Moved
